### ISSUE TITLE
Missing batch in the Gem

### ISSUE THREAD

**Issue by StefanoMartin** [crate/crate_ruby#17]
I noticed that in the gem 0.0.8, the following command does not work:

```
    bulk_args = [
  [1, "Post 1", {:street=>'1010 W 2nd Ave', :city=>'New York'}, ['foo','bar']],
  [2, "Post 2", {:street=>'1010 W 2nd Ave', :city=>'San Fran'}, []]
]
  @client.execute("insert into my_table (id, name, address, tags) VALUES (?, ?, ?, ?)", nil, bulk_args)
```

At the contrary, on the github version, this bulk command works as expected.

I would like to use this action, but I don't know if the last version of this crate_ruby is enough stable.
Will you deliver a new stable version of this gem soon?

**Comment by joemoe** [comment]
hi @StefanoMartin, at first glance i don't see any significant changes between github and the gem, but we'll check that.

**Comment by joemoe** [comment]
@StefanoMartin this should be fixed now.
