### ISSUE TITLE
[HELP] Running new releases

### ISSUE THREAD

**Issue by amotl** [crate/crate_ruby#37]
Hi @autophagy and @chaudum,

we would like to run new releases for `crate_ruby` [1] and `activerecord-crate-adapter` [2]. Can I humbly ask you to assign me [3] as a co-owner for both projects on RubyGems.org?

With kind regards,
Andreas.

/cc @hammerhead 

[1] https://rubygems.org/gems/crate_ruby
[2] https://rubygems.org/gems/activerecord-crate-adapter
[3] https://rubygems.org/profiles/amotl

**Comment by chaudum** [comment]
Hey @amotl I have added you as owner to both projects. Feel free to remove me from these projects afterwards.

**Comment by amotl** [comment]
Hi @chaudum. Thanks a stack for the quick response. I've accepted your invitation, and also added @hammerhead (https://rubygems.org/profiles/dv_ns).
